### ISSUE TITLE
使用这个EFI，无法开启集成显卡的4K分辨率

### ISSUE THREAD

**Issue by xinjing-cloud** [survive0077/M720q_Hackintosh_oc0.99#4]
使用这个EFI，无法开启集成显卡的4K分辨率，哪位告知一下如何开启4K分辨率？

**Comment by survive0077** [comment]
#1 按照这个issue中老哥的发现，您可以尝试修改config ，删除DeviceProperties —> framebuffer-stolenmem，然后重启，按option看看能否出现4k

**Comment by psyonly** [comment]
> 使用这个EFI，无法开启集成显卡的4K分辨率，哪位告知一下如何开启4K分辨率？

 确认bios是否开启默认显卡为iGPU，并且分配内存显存最大，我之前是因为分配给显卡的内存容量过小导致无法开启4K的

**Comment by xinjing-cloud** [comment]
> #1按照这个问题中老哥的发现，你可以尝试修改config，删除DeviceProperties —>framebuffer-stolenmem，然后重启，按选项看看能否出现4k

按照你的方法成功开启4k分辨率，谢谢！
